# Generated by Django 3.0 on 2020-08-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deligates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deligate',
            name='Mobno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deligate',
            name='Pincode',
            field=models.IntegerField(),
        ),
    ]
