# Generated by Django 3.0 on 2020-08-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deligates', '0002_auto_20200817_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='hopening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regno', models.CharField(default=0, max_length=100)),
                ('Industry', models.CharField(default=0, max_length=100)),
                ('Continent', models.CharField(choices=[('ASIA', 'ASIA'), ('AUSTRALIA', 'AUSTRALIA'), ('EUROPE', 'EUROPE'), ('AFRICA', 'AFRICA'), ('ANTARCTICA', 'ANTARCTICA'), ('SOUTH AMERICA', 'SOUTH AMERICA'), ('NORTH AMERICA', 'NORTH AMERICA')], default=0, max_length=100)),
                ('Country', models.CharField(default=0, max_length=100)),
                ('Province', models.CharField(default=0, max_length=100)),
                ('Department', models.CharField(choices=[('ADMIN', 'ADMIN'), ('HUMAN RESOURCES', 'HUMAN RESOURCES'), ('ACCOUNTS', 'ACCOUNTS'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('PURCHASE', 'PURCHASE'), ('PRODUCTION', 'PRODUCTION'), ('SALE & MKT', 'SALE & MKT'), ('WHARE HOUSE', 'WHARE HOUSE'), ('TIME OFFICE', 'TIME OFFICE'), ('SECURITY', 'SECURITY'), ('MAINTENANCE', 'MAINTENANCE'), ('OTHERS', 'OTHERS')], default=0, max_length=50)),
                ('Qualification', models.CharField(default=0, max_length=100)),
                ('Designation', models.CharField(choices=[('CEO', 'CEO'), ('GENERAL MANAGER', 'GENERAL MANAGER'), ('HOD', 'HOD'), ('DUTY MANAGER', 'DUTY MANAGER'), ('MANAGER', 'MANAGER'), ('ASST. MANAGER', 'ASST. MANAGER'), ('EXECUTIVE', 'EXECUTIVE'), ('OFFICER', 'OFFICER'), ('TRAINEE', 'TRAINEE'), ('OTHERS', 'OTHERS')], default=0, max_length=50)),
                ('Ctype', models.CharField(choices=[('FRESHER', 'FRESHER'), ('EXPERIENCED', 'EXPERIENCED')], default=0, max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=50)),
                ('Minexp', models.CharField(choices=[('FRESHER', 'FRESHER'), ('0-2 YEARS', '0-2 YEARS'), ('2-5 YEARS', '2-5 YEARS'), ('5-7 YEARS', '5-7 YEARS'), ('7-10', '7-10 YEARS'), ('10-12 YEARS', '10-12 YEARS'), ('12-15 YEARS', '12-15 YEARS'), ('15-20 YEARS', '15-20 YEARS'), ('20 YEARS', '20 YEARS')], default=0, max_length=50)),
                ('Budget', models.CharField(default=0, max_length=50)),
                ('DetailJD', models.TextField(default=0)),
                ('Deligate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deligates.deligate')),
            ],
        ),
    ]
