# Generated by Django 3.0 on 2020-08-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobadd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='img',
            new_name='Img',
        ),
    ]
