# Generated by Django 3.1 on 2020-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Industry', models.CharField(default=0, max_length=100)),
                ('Location', models.CharField(default=0, max_length=100)),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Orissa', 'Orissa'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim')], default=0, max_length=100)),
                ('Department', models.CharField(choices=[('ADMIN', 'ADMIN'), ('HUMAN RESOURCES', 'HUMAN RESOURCES'), ('ACCOUNTS', 'ACCOUNTS'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('PURCHASE', 'PURCHASE'), ('PRODUCTION', 'PRODUCTION'), ('SALE & MKT', 'SALE & MKT'), ('WHARE HOUSE', 'WHARE HOUSE'), ('TIME OFFICE', 'TIME OFFICE'), ('SECURITY', 'SECURITY'), ('MAINTENANCE', 'MAINTENANCE'), ('OTHERS', 'OTHERS')], default=0, max_length=50)),
                ('Designation', models.CharField(choices=[('CEO', 'CEO'), ('GENERAL MANAGER', 'GENERAL MANAGER'), ('HOD', 'HOD'), ('DUTY MANAGER', 'DUTY MANAGER'), ('MANAGER', 'MANAGER'), ('ASST. MANAGER', 'ASST. MANAGER'), ('EXECUTIVE', 'EXECUTIVE'), ('OFFICER', 'OFFICER'), ('TRAINEE', 'TRAINEE'), ('OTHERS', 'OTHERS')], default=0, max_length=50)),
                ('Ctype', models.CharField(choices=[('FRESHER', 'FRESHER'), ('EXPERIENCED', 'EXPERIENCED')], default=0, max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=50)),
                ('Minexp', models.CharField(choices=[('FRESHER', 'FRESHER'), ('0-2 YEARS', '0-2 YEARS'), ('2-5 YEARS', '2-5 YEARS'), ('5-7 YEARS', '5-7 YEARS'), ('7-10', '7-10 YEARS'), ('10-12 YEARS', '10-12 YEARS'), ('12-15 YEARS', '12-15 YEARS'), ('15-20 YEARS', '15-20 YEARS'), ('20 YEARS', '20 YEARS')], default=0, max_length=50)),
                ('Budget', models.CharField(default=0, max_length=50)),
                ('DetailJD', models.TextField(default=0)),
            ],
        ),
    ]
