# Generated by Django 3.0 on 2020-08-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsopening', '0002_auto_20200814_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='Qualification',
        ),
    ]
