# Generated by Django 3.0 on 2020-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsopening', '0005_auto_20200814_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='Regno',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
